### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by ryanbentley** [ryanbentley/freets3.net#101]
Traceback (most recent call last):
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/.env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 86, in decorated_view
    return func(*args, **kwargs)
  File "/home/.env/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 327, in __inner
    return obj(*a, **k)
  File "./app.py", line 1010, in resend_confirmation
    send_email(current_user.email, subject, html)
  File "./app.py", line 113, in send_email
    mail.send(msg)
  File "/home/.env/local/lib/python2.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/.env/local/lib/python2.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/.env/local/lib/python2.7/site-packages/flask_mail.py", line 189, in send
    list(sanitize_addresses(message.send_to)),
  File "/home/.env/local/lib/python2.7/site-packages/flask_mail.py", line 125, in sanitize_addresses
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/home/.env/local/lib/python2.7/site-packages/flask_mail.py", line 125, in <lambda>
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/home/.env/local/lib/python2.7/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
TypeError: 'NoneType' object is not iterable

**Comment by ryanbentley** [comment]
Completed in 1.0.4.4
